### ISSUE TITLE
Consider supporting Async/Await ? 

### ISSUE THREAD

**Issue by singno** [freshOS/then#10]
https://github.com/yannickl/AwaitKit

ES8 Async/Await is a wonderful feature for dealing async logic, will you consider supporting it ?

**Comment by s4cha** [comment]
@singno thanks for the suggestion, I am going to check this out :)

**Comment by singno** [comment]
@s4cha It will be very nice to have this feature!

**Comment by s4cha** [comment]
@singno Thanks a lot for pointing me towards this.
Never used Async/Await before and this would be a sweet addition indeed :)
Looking at it at the moment !

**Comment by s4cha** [comment]
Example syntaxes :
```swift
// Classic
getPhotos()
  .then(fetchPhotosInfo)
  .then(syncPhotos)

//Async/Await
let photos = try! await(getPhotos())
try! await(fetchPhotosInfo(photos))
try! await(syncPhotos())

//Async Await + error Handling
do {
  let user = try await(getPhotos()))
  try await(fetchPhotosInfo(photos)) 
  try await(syncPhotos())
} catch {
  print(error)
}
```
While the syntax is not shorter, I don't see any drawbacks to having this syntax as well.
People are also used to the Async/Await paradigm so It'll be a very welcome feature :)

In the meantime you can try it out by adding this 
```swift
typealias Async<T> = Promise<T>
typealias AsyncTask = Async<Void>

func async<T>(block:@escaping () throws -> T) -> Async<T> {
    return Promise { resolve, reject in
        do {
            let t = try block()
            resolve(t)
        } catch {
            reject(error)
        }
    }
}

func await<T>(_ promise:Promise<T>) throws -> T {
    var result: T?
    var error: Error?
    let group = DispatchGroup()
    group.enter()
    promise.then { t in
        result = t
        group.leave()
    }.onError { e in
        error = e
        group.leave()
    }
    group.wait()
    if let e = error {
        throw e
    }
    return result!
}
```
With which you'll be able to write : 
```swift
func getPhotos() -> Async<[Photo]> {
    return async {
        // Do something
        return [Photo(), Photo(), Photo()]
    }
}

// then
let photos = try! await(getPhotos())
```

Have a fantastic day !

**Comment by MontakOleg** [comment]
Nice approach! Unfortunately, this is not usable because current thread is blocked. `Await` is 'asynchronious wait', it should immediately return control to thread and execute continuation when async work is completed. It looks like `yield` in some perspective.

**Comment by s4cha** [comment]
Yep the Dispatch queue is needed to make it concurrent :)
```swift
func async<T>(block:@escaping () throws -> T) -> Async<T> {
    return Promise { resolve, reject in
        DispatchQueue(label: "testqueue", attributes: .concurrent).async {
            do {
                let t = try block()
                resolve(t)
            } catch {
                reject(error)
            }
        }
    }
}
```

**Comment by s4cha** [comment]
@singno Happy to announce that Async/await is available in the latest release 🎉 : https://github.com/freshOS/then/releases/tag/2.2.0
