### ISSUE TITLE
Cloning the library takes a long while

### ISSUE THREAD

**Issue by crarau** [freshOS/then#15]
Cloning the library takes a long while. `Receiving objects` downloads 359MB and `Resolving deltas` is very long.

```
git clone https://github.com/freshOS/then.git
Cloning into 'then'...
remote: Counting objects: 897792, done.
remote: Total 897792 (delta 0), reused 0 (delta 0), pack-reused 897792
Receiving objects: 100% (897792/897792), `359.35 MiB` | 32.12 MiB/s, done.
Resolving deltas:  59% (234493/391788)  
```

**Comment by s4cha** [comment]
Hi @crarau,

Using a beta version of the cocoapods gem to publish the library temporarily changed the remote as discussed here : https://github.com/CocoaPods/CocoaPods/issues/5771

This happened at the same time this issue occurred and we never pushed files that big, the project is supposed to be a few megabytes tops. 

So this leads me to believe that somehow a part of the Cocoapods repo got imported into the git :/ Indeed the large part of the repo is found in .git/objects/File.pack. I've tried lots of approaches till now to no avail :/ This is kinda making me crazy at the moment :)

Side note : This also happened locally on my machine on other repos, but I realised this before syncing and could delete my local project before propagating this issue.

In the meantime, you can get the bundle via the release page here :https://github.com/freshOS/then/releases

I'm very sorry for the inconvenience,

@maxkonovalov If you have any ideas ^^ In the meantime I'm going to try and reproduce what happened to try to understand how we can reverse it :/

**Comment by maxkonovalov** [comment]
I think I had a similar issue in one of my projects, somehow git started tracking Cocoapods remote instead of my repo. I fixed this by removing all remotes and re-adding them afterwards. Not sure if it's the same thing here though.

@s4cha maybe the large size of the repo can also be connected to the included zip-archive releases?

**Comment by s4cha** [comment]
This is really weird.
ykyouhei forked 5 commits ago https://github.com/ykyouhei/then and doesn't have the issue.
So it validates that it happened in the meantime but the commits in between are mostly readme updates...

Using https://rtyley.github.io/bfg-repo-cleaner/ I have tried to no avail
the 400Mb packfile is transformed into a 200Mb one which is still way too big for such a project :/
```
java -jar bfg.jar --strip-blobs-bigger-than 2M the
// then
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

**Comment by s4cha** [comment]
running 
```
git log --all --full-history -- Specs
```
Finds commits that are on the Cocoapods repo
for ex:
```
commit 94fe92aee6163817fde73a488a99ee650e8f70e8
Author: noppefoxwolf <cromteria@gmail.com>
Date:   Tue Nov 8 02:41:57 2016 -0500

    [Add] ZappingKit 0.1.6
```

Something is very wrong here...

**Comment by crarau** [comment]
I've made a fork and I'm no longer having the issue: https://github.com/crarau/then The clone of the fork is as expected, fast.

**Comment by s4cha** [comment]
Thanks to @Ptr-mat precious help, this issue is now solved!!!
2 tags from Cocoapods were copied into then repo. So deleting them removed the 450MG commits!!

**Comment by s4cha** [comment]
@crarau if you can validate we'll close the issue :)

**Comment by crarau** [comment]
All good now!

**Comment by s4cha** [comment]
:)
