### ISSUE TITLE
Memory Leaks 

### ISSUE THREAD

**Issue by ghost** [freshOS/then#24]
I've found an instance where I can produce a memory leak when using a Promise from within a new Promise:

```swift
class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        noleaky().finally {

        }

        leaky().finally {
            
        }
    }

    func leaky() -> Promise<Void> {
        return Promise { [unowned self] resolve, reject in
            self.doSomething(for: 0)
                .then(self.doSomething)
                .onError(reject)
                .finally(resolve)
        }
    }

    func noleaky() -> Promise<Void> {
        return doSomething(for: 0)
            .then(doSomething)
            .then(Promise.resolve())
    }

    func doSomething(for blah: Int) -> Promise<Int> {
        return Promise.resolve(3)
    }

}
```

I'm not sure if this is expected or not?  Sample project is attached.
[ThenLeakExample.zip](https://github.com/freshOS/then/files/935115/ThenLeakExample.zip)

**Comment by ghost** [comment]
Appears this leak happens as a result of the lack of calling .then on the Promise.  If I add in the .then call then no more leak:

`leaky().then { _ in }.finally { }`

**Comment by s4cha** [comment]
@cartermike, Thanks a ton for reporting these issues and taking the time to provide a sample project. I'm back on monday and will take a look :)

**Comment by s4cha** [comment]
@cartermike 

I've been able to reproduce the retain cycle using only:

```swift
 func leaky() -> Promise<Void> {
    return Promise.resolve()
}
```
As you mentioned, it only happens with `finally` and `onError`, not with `then`.
Weirdly enough, this only seem to happen in a synchronous setting. If you use :

```swift
func leaky() -> Promise<Void> {
    return Promise { r, _ in
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(3), execute: {
            r()
        })
    }
}
```
No retain cycle !


Linking against the code and enabling `Malloc Stack`  (edit scheme> Logging: Malloc Stack) give us some hints
<img width="1035" alt="screen shot 2017-04-24 at 14 24 28" src="https://cloud.githubusercontent.com/assets/1812953/25336935/f35a817a-28f9-11e7-8698-a77539a66c1d.png">

Looks like a retain cycle here :) Trying to get a fix and I will keep you updated :)

**Comment by s4cha** [comment]
Well looks like using : 
```swift
blocks.progress.append({ [weak p] f in
    p?.progressPromise(f)
})
```
in both `Promise+Error` and `Promise+Finally` files solve the retain cycle. now let see if the unit tests still pass :)

**Comment by s4cha** [comment]
Well the test still pass but, looks like they don't cover that part of the code so I'm going to dig into this to make sure we don't break anything.

**Comment by s4cha** [comment]
Well, using weak is not a good strategy, since we do want to retain the promise until it is fulfilled. 
P1 -retains-> P2 - retains -> P3.
when P1 fulfills, the chain should be released.
I think thee issue here is that progress is registered no matter what.
 If we move the `blocks.progress.append(p.progressPromise)` into the `pending:` case, it stops retaining the promise after its fulfilment. 
That actually explains the fact that this issue only happens in a synchronous setting.

**Comment by s4cha** [comment]
```diff
diff --git a/Source/Promise+Error.swift b/Source/Promise+Error.swift
index 2bc8ec3..fb591dc 100644
--- a/Source/Promise+Error.swift
+++ b/Source/Promise+Error.swift
@@ -34,8 +34,8 @@ public extension Promise {
             blocks.success.append({ _ in
                 p.resolvePromise()
             })
-            blocks.progress.append(p.progressPromise)
         }
+        blocks.progress.append(p.progressPromise)
         p.start()
         passAlongFirstPromiseStartFunctionAndStateTo(p)
         return p
diff --git a/Source/Promise+Finally.swift b/Source/Promise+Finally.swift
index d47322d..691cdc3 100644
--- a/Source/Promise+Finally.swift
+++ b/Source/Promise+Finally.swift
@@ -29,8 +29,8 @@ public extension Promise {
             blocks.success.append({ _ in
                 p.resolvePromise(block())
             })
-            blocks.progress.append(p.progressPromise)
         }
+        blocks.progress.append(p.progressPromise)
         p.start()
         passAlongFirstPromiseStartFunctionAndStateTo(p)
         return p
```
@cartermike can you confirm this solves your retain cycle ?

**Comment by ghost** [comment]
Absolutely I will -- give me an hour or so.

**Comment by ghost** [comment]
@s4cha ok looks like this definitely fixes the issues with promises that never call then leaking -- i.e. what is in the sample project I attached.  So thats good news.  It did not do anything to quell all the other Promise leaks that I have all over my app through which I reported via freshOS/then#25

I don't have a sample project to reproduce those exactly yet.

**Comment by s4cha** [comment]
@cartermike Sweet!. As for the other issue you reported, I'm going to instrument check on the apps I'm working on to see If I have something similar.
Hopefully, we can can have an update that fixes it all by the end of the week.
Thanks a ton for your help and time :)
