### ISSUE TITLE
Synchronous promises don't chain properly

### ISSUE THREAD

**Issue by piterlouis** [freshOS/then#3]
This is a corner case but could be interesting support it. When we have 3 promises encapsulating synchronous code, if we try to chain all of them, the chaining is not working properly.

```
func promiseA() -> Promise<Int> { 
    return Promise { resolve, reject in 
        print("Promise A")
        resolve(result: 1) 
    } 
}

func promiseB() -> Promise<Int> {
    return Promise { resolve, reject in
        print("Promise B")
        resolve(result: 2)
    }
}

func promiseC() -> Promise<Int> {
    return Promise { resolve, reject in
        print("Promise C")
        resolve(result: 3)
    }
}

```

If we chain all of them, _A_ and _B_ are executed but _C_ doesn't it:

```
promiseA().then(promiseB()).then(promiseC())
```

I think the problem in this case is in the method:

```
    public func then<X>(p:Promise<X>) -> Promise<X>{
        p.isFirstPromise = false
        successBlock = { t in p.start() }
        startPromiseIfNeeded()
        return p
    }
```

When _then_ is executed over **promiseA**, is defined the _successBlock_ and _startPromiseIfNeeded_ provokes **promiseA** starts, at the end of promiseA the _successBlock_ is executed and **promiseB** starts although as all the code is synchronous _promiseA_ and _promiseB_ are executed in the same cycle while _promiseB_ still doesn't have a _successBlock_ assigned to execute **promiseC**. So when _then_ is executed over _promiseB_, this is already started and fulfilled, _startPromiseIfNeeded_ never calls _start_.

I think a possible solution would be the next code although I'm not completely confident about it

```
    public func then<X>(p:Promise<X>) -> Promise<X>{
        p.isFirstPromise = false
        if state == .Fulfilled {
            p.start()
        } else {
            successBlock = { t in p.start() }
            startPromiseIfNeeded()
        }
        return p
    }
```

Really this is a corner case, because per definition a Promise encapsulates some asynchronous operation and in this situation we are encapsulating synchronous operations, but could be interesting because some times we need to simulate the results of async operations inside Promises.

**Comment by s4cha** [comment]
@piterlouis this is brilliant! Even if we usually use Async code in promises, this definitely is a bug indeed.
I can reproduce it on my end and your fix works like a charm :) 
Would you mind creating a pull request for this?
Thank you so much for your help :+1:

**Comment by s4cha** [comment]
By the way I could reproduce the exact same bug with the other syntax below :

``` swift
promiseA().then { _ -> Promise<Int> in
    return promiseB()
}.then { _ -> Promise<Int> in
    return promiseC()
}.then {  r in
    print(r)
}
```

which should be the exact equivalent than `promiseA().then(promiseB()).then(promiseC())`.

Once again it works perfectly if promiseA is Asynchronous but not if A is synchronous. This will need a separate fix though.

**Comment by s4cha** [comment]
Actually we need to fix this further down, as explained before, the two syntaxes should do the same. so we rewrote the function taking a promise as a parameter like so : 

``` swift
public func then<X>(p:Promise<X>) -> Promise<X>{
    return then { _ in p }
}
```

Now our fix (yet to be found) will fix the two issues described above :)

**Comment by s4cha** [comment]
Hey @piterlouis, we just pushed a fix on "dev" branch, could you confirm that it fixes your issue?

**Comment by piterlouis** [comment]
Ey @s4cha, the fix works perfect!. Thanks you a lot for your code and time!!

**Comment by chetem** [comment]
I was having this same issue, glad to see it fixed! Any chance the changes will be pushed up to Cocoapods?

**Comment by s4cha** [comment]
@chetem Indeed this wasn't pushed to CocoaPods. Can you confirm this is fixed?

**Comment by chetem** [comment]
Yep! I used the latest source code in one of my projects and everything seems to be working as expected!

**Comment by s4cha** [comment]
@chetem great !
