### ISSUE TITLE
Ambiguous use of 'init(callback:)'

### ISSUE THREAD

**Issue by ntkon** [freshOS/then#42]
I'm trying to use Stevia and ws and am getting the following error in this included pod:

`.../Pods/thenPromise/Source/Promise+Delay.swift:30:16: Ambiguous use of 'init(callback:)'`

I've tried the usual update/install of pods but no joy. Any advise would be appreciated as I've not used these libraries before and was just starting to like it, but couldn't compile. 

When I tried to use the freshOS starter project I got: `Module compiled with Swift 4.0 cannot be imported in Swift 4.1`

Thanks

**Comment by sdrpa** [comment]
Check: [Xcode 9.3 & Swift 4.1](https://github.com/freshOS/then/releases/tag/4.0.0)

Promises calls like this:
```
func foo() -> Promise<Void> {
    return Promise { resolve, _ in
      // code...
  }
}
```
Will now need to be disambiguated like so:
```
func foo() -> Promise<Void> {
    return Promise { (resolve: @escaping () -> Void, _) in
      // code...
  }
}
```

**Comment by ntkon** [comment]
Thanks, I solved the problem as described in [https://github.com/freshOS/ws/issues/52](WS issues) by vimask.

**Comment by s4cha** [comment]
@sdrpa Thanks for chiming in on this one :)
Closing this since it looks like it has been solved, feel free to reopen if needed.
