### ISSUE TITLE
can oc do it?

### ISSUE THREAD

**Issue by iamlion** [freshOS/then#43]

**Comment by cfanfs** [comment]
I think this repo is for swift only. 😴

**Comment by s4cha** [comment]
@iamlion oc is for "Objective-C" ? It might be usable from there, never tried to be honest. But the repo is swift only and we have no plans to improve Obj-C compatibility since Swift is the way forward :)

**Comment by s4cha** [comment]
@iamlion any news?

**Comment by iamlion** [comment]
i think it working like “nodejs：  await new Promise(function(reslove,reject){ reslove({"key":"hello world"}); });”
but it doesn't work ： （

**Comment by s4cha** [comment]
@iamlion Have you been able to use it? If you have another problem unrelated to objective C, please open a new issue, closing this for now :)
