### ISSUE TITLE
Add @discardableResult to await

### ISSUE THREAD

**Issue by mylemans** [freshOS/then#44]
Would it be possible for you to add @discardableResult to wait? 

It generates a warning if we just want to try await a function whose return value we do not care about.

**Comment by mylemans** [comment]
For now I resolved it by making a global func named 'doing' doing the exact same thing as await :P

try doing(...) felt good enough

**Comment by s4cha** [comment]
@mylemans I had never run into the use case personally but it seems like a reasonable thing :)
I'm going to add it for the next version

**Comment by mylemans** [comment]
Thanks, it's appreciated 👍

**Comment by s4cha** [comment]
@mylemans this is up in https://github.com/freshOS/then/releases/tag/4.1.1 :)
