### ISSUE TITLE
Data race

### ISSUE THREAD

**Issue by green-caterpillar** [freshOS/then#45]
Thread sanitizer is often complains about data race in "_synchronize" function:
```swift
private let lockQueueSpecificKey = DispatchSpecificKey<Void>()
private lazy var lockQueue: DispatchQueue = {
	let queue = DispatchQueue(label: "com.freshOS.then.lockQueue", qos: .userInitiated)
	queue.setSpecific(key: self.lockQueueSpecificKey, value: ())
	return queue
}()

private func _synchronize<U>(_ action: () -> U) -> U {
	if DispatchQueue.getSpecific(key: lockQueueSpecificKey) != nil {
		return action()
	} else {
		return lockQueue.sync(execute: action) // <- Data race detected here
	}
}
```
That's probably due to using lockQueue from many threads simultaneously. And lockQueue is a lazily computed variable, which is not thread safe.

**Comment by cfanfs** [comment]
That's true. Thank you for your feedback.

**Comment by cfanfs** [comment]
Please check PR #46 if it works correctly. Thanks!

**Comment by s4cha** [comment]
@green-caterpillar this is now in https://github.com/freshOS/then/releases/tag/4.1.1 :)

**Comment by s4cha** [comment]
Closing this for now, feel free to reopen if needed :)
