### ISSUE TITLE
"Incompatible Swift version - framework was built with 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

### ISSUE THREAD

**Issue by walkertop** [freshOS/then#49]
carthage install method: [ ] .pkg, [ x] homebrew, [ ] source
which carthage:/usr/local/bin/carthage
carthage version: 0.31.2
xcodebuild -version: Xcode 10.1\Build version 10B61
Are you using --no-buildno
Are you using --no-use-binariesno
Are you using --use-submodulesno
Are you using --cache-buildsno
Are you using --new-resolverno

**cartfile**
```
github "freshOS/then" "4.2.0"

```

```
*** Downloading then.framework binary at "Xcode10 & Swift 4.2"
***  Skipped installing then.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

```

**Comment by walkertop** [comment]
@s4cha can u slove my issue?

**Comment by florianbuerger** [comment]
@walkertop Until this is solved in the framework itself you can use the `--no-use-binaries` flag for carthage to build it with the right toolchain so the version will match.

**Comment by walkertop** [comment]
@florianbuerger that's ok,3ks

**Comment by s4cha** [comment]
@walkertop version 4.2.1 is now pre-built with the new Xcode https://github.com/freshOS/then/releases/tag/4.2.1, let me know if that works for you :)

**Comment by walkertop** [comment]
fine to me,thanks
