### ISSUE TITLE
WhenAll always succeeds

### ISSUE THREAD

**Issue by maxkonovalov** [freshOS/then#5]
`whenAll` always calls `then` block, disregarding its inner promises success or fail:

``` swift
let promise1 = Promise<Void> { (resolve, reject) in
    print("promise1")
    reject(NSError())
}

let promise2 = Promise<Void> { (resolve, reject) in
    print("promise2")
    reject(NSError())
}

whenAll(promise1, promise2)
    .then { _ in
        print("whenAll success")
    }
    .onError { _ in
        print("whenAll failed")
    }
    .finally { _ in
        print("whenAll finally")
}
```

Output:

```
promise1
promise2
whenAll success
whenAll finally
```

Is this by design? Would be good to get `onError` called when one of the promises fails.

**Comment by s4cha** [comment]
Hi @maxkonovalov 
Good catch :)
whenAll now calls `onError` if one of the promises fail -> f9a1cee037c7188bd768505fa05060d9c5709955
Let me know if that's ok with you and we'll tag a new version, 

Have a nice day,

**Comment by maxkonovalov** [comment]
Awesome! It works now as expected, thanks! 😀

**Comment by s4cha** [comment]
Great!
This is now fixed in 1.4.1

**Comment by umeshjavastar** [comment]
I have a little bit of problem related to above discussion,

whenAll execute two promises,
1.promise 1
2.promise 2

How to know which promise failed?? if Any

OR

 How to handle if any of these promise failed due to network lost?

**Comment by maxkonovalov** [comment]
Hi @umeshjavastar! 

The logic for `whenAll` is that if any promise fails, the whole group fails. The current logic is that the **last** promise that fails propagates its error to the `whenAll` completion. BTW, I think this behavior should be reversed so that the first failed promise cancels the whole group and outputs its error - @s4cha what do you think? Is it possible at all to cancel the promises somehow?

Regarding the questions,
It is currently impossible to differentiate which promise has failed, only by the error itself (if you can use different errors for different promises in your code). Otherwise I think, to tell them apart would require adding some kind of label to a Promise object.

So, as I see it, the general usage scenario for `whenAll` is that the promises in your group neither depend on each other, nor it is important which one exactly has failed – which means either they all succeed and your app flow continues, or if any of them fails, the flow stops and outputs the error.
If your usage scenario depends on knowing the _exact_ result of a promise to keep going, then I'd suggest simply chaining your promises in a sequence to keep track of the things.
