### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by MoveUpwardsDev** [freshOS/then#53]
Thank you for providing such a great library. 

Nevertheless the name shall be update in CamelCase

```swift
import Then
```

looks better than

```swift
import then
```

**Comment by s4cha** [comment]
@MoveUpwardsDev this is a very good point. I like the idea. I'm going to update the lib to swift 5.1 first, which is quite urgent. I have to assess the implications of such a change on things like Cocoapods if we apply it to the library as a whole, and not just the framework name :)

**Comment by s4cha** [comment]
@MoveUpwardsDev This is now live in latest version :)
