### ISSUE TITLE
Mapping a response to `Void`

### ISSUE THREAD

**Issue by nodediggity** [freshOS/then#63]
I was thinking perhaps there may be some benefit to mapping a promise result to `Void`. 

For example, I do not care about the result of a task, only that it has completed. 

I use the `VIPER` pattern quite heavily and a lot of the time I simply want my components to know another task has finished, without needing to give it context of models, or responses etc.

This could be a fairly simple addition - 

```swift
extension Promise {
    func asVoid() -> Promise<Void> {
        return .resolve(())
    }
}
```

This would allow me to have chains within the call that had context of the response and made use of it's model, but the original trigger could simply move along to the next promise in it's `async` block.

**Comment by s4cha** [comment]
@nodediggity This is a very good point 👌 . I actually have this extension in my own project.
Can you explain why you closed the issue ?
```swift
extension Promise {
    public func toVoid() -> Promise<Void> {
        return self.then { _ -> Void in }
    }
}
```
