### ISSUE TITLE
Xcode 11.2.1: fatal error: Unexpected Swift version

### ISSUE THREAD

**Issue by julestburt** [freshOS/then#64]
I seem unable to compile the current master with the latest release of Xcode. I have a log if that's helpful - but am not sure if 11.2.1 is officially supported yet or not?

Any advice would be appreciated. Thx

export variant=normal
    /bin/sh -c /Users/jenkins/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/then/5.1.1/Build/Intermediates.noindex/ArchiveIntermediates/then/IntermediateBuildFilesPath/Then.build/Release-iphoneos/Then.build/Script-9962ADBE1D58534D005769CD.sh
fatal error: Unexpected Swift version: file /tmp/swiftlint-20170407-4750-thxk9c/Source/SwiftLintFramework/Models/SwiftVersion.swift, line 38
/Users/jenkins/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/then/5.1.1/Build/Intermediates.noindex/ArchiveIntermediates/then/IntermediateBuildFilesPath/Then.build/Release-iphoneos/Then.build/Script-9962ADBE1D58534D005769CD.sh: line 6: 42465 Illegal instruction: 4  swiftlint
Command PhaseScriptExecution failed with a nonzero exit code

** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/jenkins/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/then/5.1.1/Build/Intermediates.noindex/ArchiveIntermediates/then/IntermediateBuildFilesPath/Then.build/Release-iphoneos/Then.build/Script-9962ADBE1D58534D005769CD.sh
(1 failure)

**Comment by s4cha** [comment]
@julestburt Thanks for reporting this, I'm going to try to build it with the latest version and let you know how it goes.

**Comment by s4cha** [comment]
@julestburt the latest version is 5.1.2 has been built with the latest Xcode (11.3) & Swift 5.1.3. https://github.com/freshOS/Then/releases/tag/5.1.2
Let me know if that solves your issue.

**Comment by julestburt** [comment]
Yes, this seems to have resolve. Much appreciated!!
