### ISSUE TITLE
Warning Xcode 12: Simulator deployment target ‘IPHONEOS_DEPLOYMENT_TARGET’ is set to 8.0

### ISSUE THREAD

**Issue by simonbromberg** [freshOS/then#70]
Warning in Xcode 12

> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99.

Would be nice to silence this warning.

iOS 8 support can presumably be safely dropped?

![image](https://user-images.githubusercontent.com/2942298/100768034-6d96b080-33c8-11eb-96ca-e85c227f1076.png)

**Comment by s4cha** [comment]
Thanks for reporting, this is now fixed in https://github.com/freshOS/Then/releases/tag/6.0.0
