### ISSUE TITLE
How about support iOS 15? 

### ISSUE THREAD

**Issue by cillyfly** [freshOS/then#71]
is any schedule for support iOS15?

**Comment by hllGitHub** [comment]
Looking forward to the support of iOS15.

**Comment by dasoga** [comment]
Same here! 🙋🏽‍♂️

**Comment by cillyfly** [comment]
https://github.com/freshOS/Then/pull/72

**Comment by s4cha** [comment]
@cillyfly, @hllGitHub, @dasoga  #72 has been merged and is live in https://github.com/freshOS/Then/releases/tag/6.0.0, let me know if that works for you :)
