### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by DmitryShapovalov** [freshOS/then#75]
Hello,

At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs etc will need to provide a privacy manifest.
Does Then need to include this manifest?

Here are some useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
https://developer.apple.com/videos/play/wwdc2023/10060/

Thanks

**Comment by s4cha** [comment]
Hey @DmitryShapovalov, Thanks for the update, pretty busy at the moment but I am going to check it out this week. Then doesn't collect anything so it should be pretty straightforward to implement :)

**Comment by obushnell** [comment]
In the apps I have released, the privacy manifest only needs to deal with collected data. If your app doesn't collect any data, the privacy manifest can simply say that. As Then does not collect data it is not relevant to the privacy manifest.

**Comment by s4cha** [comment]
Hey @DmitryShapovalov, Is this blocking you in any way, like, are you getting an Appstore warning of some sort or something? Apple is pretty vague about this and I'm not 100% sure open source packages built via SPM need this.

**Comment by DmitryShapovalov** [comment]
> Hey @DmitryShapovalov, Is this blocking you in any way, like, are you getting an Appstore warning of some sort or something? Apple is pretty vague about this and I'm not 100% sure open source packages built via SPM need this.

Hello, not yet, just wondering to be prepared for the deadline for having Privacy Manifest.

Accroding to the news from Apple:
> Starting March 13: If you upload a new or updated app to App Store Connect that uses an API requiring approved reasons, we’ll send you an email letting you know if you’re missing reasons in your app’s privacy manifest. This is in addition to the existing notification in App Store Connect.

> Starting May 1: You’ll need to include approved reasons for the listed APIs used by your app’s code to upload a new or updated app to App Store Connect. If you’re not using an API for an allowed reason, please find an alternative. And if you add a new third-party SDK that’s on the list of commonly used third-party SDKs, these API, privacy manifest, and signature requirements will apply to that SDK. Make sure to use a version of the SDK that includes its privacy manifest and note that signatures are also required when the SDK is added as a binary dependency.

Link: https://developer.apple.com/news/?id=3d8a9yyh

The deadline date is 1st of May.

Thanks

**Comment by s4cha** [comment]
Should be good with [7.0.1](https://github.com/freshOS/Then/releases/tag/7.0.1). We'll see if things go smoothly :)

**Comment by DmitryShapovalov** [comment]
Thank you!

**Comment by s4cha** [comment]
Closing this for now, feel free to reopen if any issue arises :)
