### ISSUE TITLE
swift 3 with pod file

### ISSUE THREAD

**Issue by umeshjavastar** [freshOS/then#8]
hello I am using pod in swift 3

`pod 'thenPromise', :git => 'https://github.com/freshOS/then.git', :branch => 'swift3' #swift 3`

but it doesn't work can you tell me right syntax

**Comment by s4cha** [comment]
Hello @umeshjavastar there is nothing wrong with your Podfile as far as I can tell.  We have an issue with the swift3 version of then indeed but we're on it :)
I'll ping you when it's fixed, hopefully tomorrow. Have a great day,

**Comment by umeshjavastar** [comment]
Thanks,
I am waiting for new version update

**Comment by s4cha** [comment]
Hi @umeshjavastar, swift3 version is now out
Here is a `Podfile` version that will pull the latest (swift3) version.

```
target "MyApp" do
  pod 'thenPromise', :git => 'https://github.com/freshOS/then.git'
  use_frameworks!
end
```

Let me know how it goes :)

**Comment by umeshjavastar** [comment]
Thanks its working

**Comment by s4cha** [comment]
Awesome!
